

<div style="text-align: center; padding: 30px 10px;">

<h1 style="color:#ff7500; font-size: 24px; margin-bottom: 10px;">
МФТИ ФПМИ
</h1>

<h2 style="font-size: 30px; margin-top: 5px;">
Практикум Python - Phys&Math Поток
</h2>

<hr style="width: 60%; border: 1px solid #10069f; margin: 25px auto;">

<h3 style="font-size: 36px;">
5. Numpy.linalg
</h3>

<p style="margin-top: 20px;">
<strong>Дата:</strong> 03-05 марта 2026 года<br>
</p>

<p style="margin-top: 25px;">
Данный ноутбук является частью серии семинаров по курсу  
<em>«Практикум Python»</em> и предназначен для учебных и образовательных целей.
</p>

</div>


Тема нашего семинара касается реализации линейной алгебры в Python, да и в языках программирования вообще. Не секрет, что большинство численных уравнений фактически являются классическими задачами из области линейной алгебры, поэтому это особенно важно для математиков и физиков, но полезно абсолютно для всех.

Пожалуй, начнем с истории.

*Дисклеймер*

Далее вас ждет большое количество терминологии из области линейной алгебры. Если вам что-то из этого интересно, то мы предлагаем самостоятельно разобраться, иначе мы украдем работу у ваших преподавателей из кафедры высшей математики и кафедры информатики и вычислительной математики, что является плохим поступком.



# **История программирования линейной алгебры**

Традиционно, языком научного программирования являлся FORTRAN (Formula Translating system). Это было связано с тем, что в отличие от низкоуровневых Assembly языков, все операции и названия в FORTRAN были приближены к терминологии математики и алгебры, что позволяло легко догадываться, что именно происходит в коде. Кроме того, FORTRAN изначально был площадкой для численных операций, поэтому там была оптимизация по памяти и времени и работали базовые алгоритмы оптимизации. Вообще, FORTRAN появился в 1957 году и успешно развивается и по сей день. Ныне же, FORTRAN не так популярен, поскольку основная его цель - математические операции, а, например, тот же Python позволяет работать и с математикой и наукой в целом, при этом являясь площадкой для функционального, объектно-ориентированного программирования, а также работать с интернетом и непосредственно с системой компьютера. Но давайте вернемся к линейной алгебре.

Все началось в далеком 1979 году в виде маленькой библиотеки для языка Fortran 77 под названием Basic Linear Algebra Subprograms или BLAS. В дальнейшем библиотека дополнялась и получила трехуровневую систему.

Перед описанием каждого уровня скажем, что если далее вы увидите знак ?, то вместо него могут быть буквы S, D, C, Z - одинарная точность действительного числа, двойная точность действительного числа, одинарная точность комплексного числа, двойная точность комплексного числа.

Уровень 1 - скалярно-векторные операции

SWAP - поменять местами элементы двух векторов (x <-> y)

SCAL - поэлементно умножить вектор на скаляр y = αx

COPY - поэлементное копирование вектора в другой y = x

AXPY - поэлементное y = αx + y

DOT (DOTU для комплексных без сопряжения, DOTC - с сопряжением) - скалярное произведение, реализуемое через поэлементное умножение x * y и суммирование полученных произведений

NRM2 - евклидова норма вектора корень из DOT вектора с самим собой

ASUM - суммирование абсолютных значений в векторе

I?AMAX - индекс элемента с максимальным абсолютным значением, поиск делается напрямую сравнивая каждый следующий элемент с текущим максимумом

I?AMIN - индекс элемента с минимальным абсолютным значением, аналогично предыдущему

ROT - поворот Гивенса для двух элементов вектора x и y, который работает как x = cx + sy, y = -sx + cy (умножение на матрицу поворота, где c - cos, s - sin)

ROTG - подбор такого поворота Гивенса, чтобы занулить второй элемент, особенно важен для QR разложения матриц

ROTM - модифицированный поворот Гивенса, однопараметрический, x = (x + my)/sqrt(1+m^2), y = (-mx+y)/sqrt(1+m^2), еще более оптимизирован для ускорения QR разложения

ROTMG - подбор модифицированного поворота, зануляющий второй элемент

Теперь на базе полученных функций мы можем перейти дальше, исходя из следующей логики. Матрица - это набор векторов. Работа с матрицами - это работа с векторами. Поэтому следующий уровень будет основан на предыдущем.

Уровень 2 - матрично-векторные операции

GEMV - умножение матрицы на вектор в общем случае y = αAx + βy, считается поэлементно, где каждый элемент - это скалярное произведение соответствующей строки матрицы на вектор x, и AXPY

GBMV - умножение ленточной матрицы m x n на вектор, оптимизированнее, поскольку ленточная матрица хранится отдельно в виде двумерного массива данных (KL + KU + 1) x n, где KL - количество ненулевых диагоналей под главной диагональю, а KU - над главной диагональю. Эта оптимизация очень важна, поскольку во многих задачах численного решения дифференциальных уравнений матрицы трехдиагональные или пятидиагональные.

GER - общее обновление матрицы первого ранга, A = A + α x^T y, считается поэлементно.

SYMV - умножение симметричной матрицы на вектор, оптимизированнее, поскольку достаточно умножить только нижнетреугольную матрицу. Формула примерно такая Ax = A_LT x + (x^T A_LT)^T - diag(A) x. Соответственно, достаточно хранить только нижнюю диагональ.

SPMV - умножение симметричной матрицы на вектор, с предварительным превращением нижнего треугольника в одномерный вектор. В целом быстрее, чем SYMV, но это зависит от архитектуры.

SYR - обновление симметричной матрицы первого ранга, Α = Α + α x^Tx, быстрее поскольку достаточно выполнить для нижнего треугольника.

SYR2 - обновление симметричной матрицы второго ранга, A = A + α (x^Ty + y^Tx)

TRMV - умножение треугольной матрицы на вектор, оптимизированнее, потому что не тратит время на умножение нулей

TRSV - решение треугольной системы Ax=b, легко в силу треугольности, основа LU разложения и разложения Холецкого

Аналогично формулируются HEMV, HBMV, HPMV, HER, HER2, HPR, HPR2 для эрмитовых матриц и TBMV, TPMV, TBSV, TPSV

Теперь посмотрим на умножение матриц с точки зрения набора умножений матрицы на столбцы второй матрицы. Таким образом, матричное перемножение сводится ко второму уровню.

Уровень 3 - матрично-матричные операции

GEMM - общее перемножение матриц, C = αAB + βC

SYMM - тоже, что сверху, но А - симметричная

HEMM - тоже, но для А - эрмитовой

TRMM - тоже, но А - треугольная

TRSM - решение AX = B, где А - треугольная

SYRK - обновление симметрично матрицы k-го ранга, C = αAA^T + βC

SYRK2 - обновление с двумя матрицами, C = α(AB^T+BA^T) + βC

Таким образом, BLAS создал набор простых комманд, которые в дальнейшем удобным образом передались во все языки программирования, начиная с C и переходя в MATLAB и другие.

Годы идут, программирование не стоит на месте. В 1992 году пишется новая библиотека на основе BLAS, которая называется LAPACK - Linear Algebra Package. Здесь уже решаются общие задачи и делаются все известные разложения.

GESV - точное решение для AX = B, пользуется LU разложением и TRSM из BLAS

POSV - точное решение для системы при положительно определенной симметричной матрице А

GELS - решение методом наименьших квадратов AX = B для переопределенной или недоопределенной системы, пользуется QR разложением и GEMM из BLAS

GELSD - тоже самое, но SVD разложение вместо QR

GEEV - нахождение собственных значений и собственных векторов общей матрицы, использует преобразование Хессенберга, разложение Шура и вообще много всего, вершина линейной алгебры

SYEV - тоже самое для симметричных матриц

HEEV - тоже самое для эрмитовых матриц

GETRF - LU разложение, основано на TRSM и GEMM

POTRF - разложение Холецкого

GEQRF - QR разложение

GEBRD - бидиагональное разложение

GEHRD - приведение к форме Хессенберга

GETRI - обратная матрица через LU

POTRI - обратная матрица через Холецкого

GETRS - решение через LU

POTRS - решение через Холецкого

GEBAL - балансировка матрицы элементарными преобразованиями над строками, использует 1 уровень BLAS

SYTRD - приведение симметричной матрицы к трехдиагональной

LANGE - норма матрицы

LARNV - генерация случайных векторов

LASWP - перестановка строк или столбцов матрицы

Таким образом, на этом этапе почти все известные задачи базовй линейной алгебры были решены.

"Зачем придумывать велосипед?" - подумал уже знакомый нам Travis Oliphant и написал подбиблиотеку numpy.linalg таким образом, что при вызове функций оттуда реализуется соответствующая операция из BLAS или LAPACK. Познакомимся теперь с ними поближе.

# **Основной функционал NumPy Linear Algebra**

In [ ]:
import numpy as np
from numpy import linalg as la

Ключевое слово from позволяет импортировать конкретную подбиблиотеку, здесь оно, честно говоря, для красоты.

Сначала зададим матрицы A и B для дальнейшей работы с ними.

In [ ]:
A = (np.arange(9)+1).reshape(3,3)
B = np.eye(3) + 2

Теперь начнем с самого простого. Матричное умножение в Python делается через np.matmul или его синтаксический сахар - @.

In [ ]:
A @ B

array([[13., 14., 15.],
       [34., 35., 36.],
       [55., 56., 57.]])

Здесь автоматически подключается GEMM из BLAS Level 3. Сам по себе NumPy не проверяет тип матрицы, чтобы ускорить алгоритм, поэтому для матриц n x n требуется O(n^3) операций. Ускорение есть в SciPy в зависимости от типа матрицы, но пока не будем об этом. Отметим, также, что при работе с многомерными массивами матричное умножение происходит для двух последних мерностей, то есть считается, что у вас большой набор матриц, которые надо между собой перемножать.

Дальше нас интересует обратная матрица. Реализуется она через GETRI из LAPACK.

In [ ]:
la.inv(A)

LinAlgError: Singular matrix

О нет, наша же матрица сингулярная, то есть ее детерминант равен нулю, почему же нам сначала не проверить, что это действительно так.

In [ ]:
la.det(A)

np.float64(0.0)

Нахождение детерминанта происходит за счет GETRF из LAPACK, а далее для треугольных матриц детерминант - это произведение всех диагональных элементов. Всего O(n^3) операций.

In [ ]:
if la.det(B) != 0:
  print(la.inv(B))

[[ 0.71428571 -0.28571429 -0.28571429]
 [-0.28571429  0.71428571 -0.28571429]
 [-0.28571429 -0.28571429  0.71428571]]


Здесь важно отметить, что обратная матрица считается за O(n^3) времени в том случае, если у вас матрица существенно несингулярная. Если же вы очень близко к тому, чтобы был 0, то резко станет тяжелее жить, поэтому будьте осторожны.

In [ ]:
la.inv(A + np.eye(3)*1e-10)

array([[ 1.66666653e+09, -3.33333306e+09,  1.66666653e+09],
       [-3.33333306e+09,  6.66666612e+09, -3.33333306e+09],
       [ 1.66666653e+09, -3.33333306e+09,  1.66666653e+09]])

На всякий случай желательно проверять, что ваша матрица не сингулярная, иначе LinAlgError, специальное исключение нашей подбиблиотеки, убьет ваш код, а ваш ассистент поставит вам плохую оценку.

Одной из причин почему так важно находить обратную матрицу - это решение матричных уравнений. Действительно, поставим перед собой задачу решить BX = A, тогда умножая слева на inv(B) получим X = inv(B)A. Проверим, что все действительно так и сравним с решением матричных уравнений из NumPy Linear Algebra.

Решение матричных уравнений основано на GESV из LAPACK.

In [ ]:
la.solve(B, A)

array([[-2.42857143, -2.28571429, -2.14285714],
       [ 0.57142857,  0.71428571,  0.85714286],
       [ 3.57142857,  3.71428571,  3.85714286]])

In [ ]:
la.solve(B, A) - la.inv(B) @ A

array([[ 0.00000000e+00,  0.00000000e+00,  4.44089210e-16],
       [-1.11022302e-16,  4.44089210e-16, -2.22044605e-16],
       [ 4.44089210e-16, -4.44089210e-16,  4.44089210e-16]])

Решать через solve можно как уравнение с правой частью вектором, так и с матрицей. solve работает за O(n^3) операций. Отметим, что solve ищет именно точное решение, в случае когда ваша система не является недоопределенной или переопределенной, поэтому первая матрица должна быть несингулярной и квадратной.

Вообще решение матричных уравнений - это фундаментальная задача, пригождающая почти всюду, поэтому обращаем на это особое внимание.

Другой фундаментальной задачей является разложение матриц для их дальнейшего анализа или использования. Всяко легче работать с красивой симметричной или треугольной матрицей, чем с матрицей в общем виде.

Начнем с разложения Холецкого на основе POTRS.

In [ ]:
la.cholesky(A)

LinAlgError: Matrix is not positive definite

Ах да, разложение Холецкого и POTRS у нас же работали только с положительно определенными, симметричными матрицами. У нас как раз есть одна такая.

In [ ]:
la.cholesky(B)

array([[1.73205081, 0.        , 0.        ],
       [1.15470054, 1.29099445, 0.        ],
       [1.15470054, 0.51639778, 1.18321596]])

*Справка*

Разложение Холецкого - это тоже самое LU разложение только для симметричных матриц.

In [ ]:
B - la.cholesky(B) @ la.cholesky(B).T

array([[4.4408921e-16, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 4.4408921e-16, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00]])

Как видим, все правильно работает. Отметим, что разложение Холецкого требует O(n^3) операций. Разложение Холецкого позволяет эффективно решить матричное уравнение AX = B. Для этого достаточно умножить справа уравнение на A^T и получить (A^TA)X = A^TB. Таким образом, с левой стороны у нас симметричная и положительно определенная матрица, если матрица А полного столбцового ранга, то есть несингулярная. Далее разложение Холецкого позволяет разбить задачу на два этапа. L(L^TX) = A^TB, откуда L^TX = C. Обе задачи с треугольными матрицами, для которых как мы помним, все легче и быстрее.

*Важно*

la.cholesky(B, upper=False) по умолчанию. upper = True выдает верхнетруегольную матрицу.

Далее у нас в программе SVD разложение.

In [ ]:
la.svd(A)

SVDResult(U=array([[-0.21483724,  0.88723069,  0.40824829],
       [-0.52058739,  0.24964395, -0.81649658],
       [-0.82633754, -0.38794278,  0.40824829]]), S=array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]), Vh=array([[-0.47967118, -0.57236779, -0.66506441],
       [-0.77669099, -0.07568647,  0.62531805],
       [-0.40824829,  0.81649658, -0.40824829]]))

Довольно странный ответ, давайте разбираться.

In [ ]:
type(la.svd(A))

numpy.linalg._linalg.SVDResult

Получается для SVD разложения придумали отдельный тип, что на самом деле удобно для того, чтобы написать так.

In [ ]:
U, S, Vh = la.svd(A)
print(U, S, Vh, sep = '\n')
print(type(U), type(S), type(Vh), sep = '\n')

[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
[1.68481034e+01 1.06836951e+00 4.41842475e-16]
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


Как видим, таким образом мы записали результаты в обычные массивы из NumPy. Проверим, что это действительно SVD разложение.

In [ ]:
A - U @ np.diag(S) @ Vh

array([[-2.22044605e-15, -4.88498131e-15, -6.66133815e-15],
       [-8.88178420e-16, -2.66453526e-15, -3.55271368e-15],
       [-2.66453526e-15, -7.10542736e-15, -7.10542736e-15]])

Отлично. SVD разложение для матрицы m x n работает за O(min(mn^2, nm^2)) операций и является основой для такой концепции как псевдообратная матрица.

In [ ]:
la.pinv(A)

array([[-6.38888889e-01, -1.66666667e-01,  3.05555556e-01],
       [-5.55555556e-02,  4.20756436e-17,  5.55555556e-02],
       [ 5.27777778e-01,  1.66666667e-01, -1.94444444e-01]])

Проверим основные тождества для псевдообратной матрицы.

In [ ]:
A @ la.pinv(A) @ A - A

array([[ 1.77635684e-15,  4.44089210e-16, -1.77635684e-15],
       [ 3.55271368e-15,  1.77635684e-15,  8.88178420e-16],
       [ 7.99360578e-15,  7.10542736e-15,  7.10542736e-15]])

In [ ]:
la.pinv(A) @ A @ la.pinv(A) - la.pinv(A)

array([[ 7.77156117e-16,  3.05311332e-16, -3.33066907e-16],
       [-6.93889390e-18,  1.49774840e-17,  2.77555756e-17],
       [-9.99200722e-16, -3.05311332e-16,  3.88578059e-16]])

In [ ]:
(A @ la.pinv(A)).T - A @ la.pinv(A)

array([[ 0.00000000e+00, -8.88178420e-16, -2.72004641e-15],
       [ 8.88178420e-16,  0.00000000e+00, -8.88178420e-16],
       [ 2.72004641e-15,  8.88178420e-16,  0.00000000e+00]])

Количество операций для нахождения псевдообратной матрицы совпадает с количеством операций в SVD. Псевдообратная матрица нужна для решения задачи AX = B методом наименьших квадратов (МНК) в случае, когда система недоопределена или переопределена. Для этого даже есть отдельная функция на основе GELS из LAPACK.

In [ ]:
la.lstsq(A, B)

(array([[-1.63888889e+00, -1.16666667e+00, -6.94444444e-01],
        [-5.55555556e-02,  2.22044605e-16,  5.55555556e-02],
        [ 1.52777778e+00,  1.16666667e+00,  8.05555556e-01]]),
 array([], dtype=float64),
 np.int32(2),
 array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]))

Нам вывели tuple из 4-х элементов:

1. Матрица X - решение методом наименьших квадратов

2. Сумма квадратов остатков ||B - AX ||^2, где норма - это вторая норма матриц. Пустая при недоопределенной системе.

3. Ранг матрицы А

4. Сингулярные числа матрицы А.

Проверим последнее.

In [ ]:
la.lstsq(A, B)[-1] - S

array([ 0.00000000e+00,  2.22044605e-16, -1.47911420e-31])

Теперь попробуем получить тоже самое решение через псевдообратную матрицу.

In [ ]:
la.lstsq(A, B)[0] - la.pinv(A) @ B

array([[ 2.22044605e-16, -4.44089210e-16, -6.66133815e-16],
       [ 1.94289029e-16,  1.38777878e-16,  6.93889390e-17],
       [ 0.00000000e+00,  6.66133815e-16,  6.66133815e-16]])

В этом и смысл псевдообратной матрицы, что уравнение AX = B заменяется на X = pinv(A)B.

Теперь, пожалуй, надо внести небольшую ясность где это вообще может понадобится. Самые популярные ответы - построение МНК решений и численное решение дифференциальных уравнений. Последнее особенно важно в физических приложениях, поскольку почти всегда построить аналитическое решение для более-менее серьезной физической задачи не представляется возможным, зато можно качественно описать происходящее через численное моделирование.

*Важно*

Если ваша система недоопределена, то у вас бесконечно много решений. lstsq выдает решение с минимальной Евклидовой нормой!

Другими полезными функциями в NumPy Linear Algebra являются:

In [ ]:
#След матрицы
la.trace(A)
#O(n) operations

np.int64(15)

След матрицы полезно знать, поскольку он не меняется при смене базиса и явным образом входит в характеристическое уравнение.

In [ ]:
#Норма матрицы
la.norm(A)
#O(n^2), можно использовать для векторных норм и получим O(n)

np.float64(16.881943016134134)

По умолчанию выбирается Фробениусова норма матрицы, которая, кстати, адекватной нормой не является.

In [ ]:
#Октаэдрическая норма
la.norm(A, ord = 1)

np.float64(18.0)

In [ ]:
#Кубическая норма
la.norm(A, ord = np.inf)

np.float64(24.0)

In [ ]:
#Евклидова норма
la.norm(A, ord = 2)

np.float64(16.84810335261421)

Норма матрицы является важной характеристикой для оценки точности решений уравнения AX = B. Дело в том, что если ваши A и B имеют погрешность dA, dB, то оценка погрешности dX делается на основе матричных норм.

In [ ]:
#Число обусловленности
la.cond(B)

np.float64(3.813147060626918e+16)

Число обусловленности - это норма матрицы помноженная на норму обратной матрицы. Опять-таки, возникает в задаче оценки погрешности решения матричного уравнения. По умолчанию берется вторая норма, но можно уточнить нужную.

In [ ]:
la.cond(B, 'fro')

np.float64(10.150902241994581)

In [ ]:
#QR - разложение, mode = 'reduced' по умолчанию, O(min(mn^2, nm^2))
la.qr(A, mode = 'reduced')

QRResult(Q=array([[-0.12309149,  0.90453403,  0.40824829],
       [-0.49236596,  0.30151134, -0.81649658],
       [-0.86164044, -0.30151134,  0.40824829]]), R=array([[-8.12403840e+00, -9.60113630e+00, -1.10782342e+01],
       [ 0.00000000e+00,  9.04534034e-01,  1.80906807e+00],
       [ 0.00000000e+00,  0.00000000e+00, -8.88178420e-16]]))

QR - разложение - это полезный инструмент разделение на ортогональную и верхнетреугольную матрицу. Основная польза в том, что в рамках разложения чаще всего уменьшается число обусловленности, что удобно для дальнейшей работы с матрицей.

Теперь наконец венец творения - собственные значения и собственные вектора матриц. Тут есть аж 4 функции, которые этого добиваются.

eig - собственные значения и правые собственные вектора для квадратной матрицы

eigh - собственные значения и собственные вектора Эрмитовой или симметричной матрицы

eigvalsh - собственные значения Эрмитовой или симметричной матрицы

eigvals - собственные значения в общем случае

In [ ]:
la.eig(A)

EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))

Здесь тоже используется специальный тип, для удобства пишем так.

In [ ]:
vals, vectors = la.eig(A)
print(vals, vectors, sep = '\n')

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [ ]:
la.eigh(B)

EighResult(eigenvalues=array([1., 1., 7.]), eigenvectors=array([[-0.81649658,  0.        , -0.57735027],
       [ 0.40824829, -0.70710678, -0.57735027],
       [ 0.40824829,  0.70710678, -0.57735027]]))

In [ ]:
valsh, vectorsh = la.eigh(B)
print(valsh, vectorsh, sep = '\n')

[1. 1. 7.]
[[-0.81649658  0.         -0.57735027]
 [ 0.40824829 -0.70710678 -0.57735027]
 [ 0.40824829  0.70710678 -0.57735027]]


In [ ]:
la.eigvalsh(B)

array([1., 1., 7.])

In [ ]:
la.eigvals(A)

array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15])

Нахождение собственных значений и собственных векторов существенно облегчает работу с матрицами. Часто для описания сложных физических процессов достаточно знать максимальное и минимальное собственное значение. С другой стороны, в базисе из собственных векторов матрица записывается как диагональ из собственных значений. Это особенно важно в области квантовой механики, хотя там нестандартное понятие векторов. Все указанные функции для спектрального анализа (нахождение собственных векторов и значений) работают за O(n^3) операций.

# **In-place computations**

Раз уж мы заговорили об оптимизированных алгоритмах решения систем линейных уравнений, то хочется поговорить о такой теме как in-place computations. In-place computations означает, что вы модифицируете объект непосрдественно, не создавая лишнюю копию куда запишите результат работы. Это позволяет оптимизироваться по памяти, но опасно если вам нужно сохранить информацию о вашем объекте.

*Важно*

Изменять in-place иммутабельный объект, очевидно, нельзя.

Наиболее часто in-place работа идет со списками в Python. Действительно, методы append, extend, insert, remove, pop, sort, reverse являются in-place. Это как мы помним было хорошо для памяти, но очень плохо, если ваш список внутри tuple.

# **Задачи**

Предварительно сгенерируем для вас веселые матрицы.

In [ ]:
A = 10 * np.random.randn(np.random.randint(1,100), np.random.randint(1,100))

In [ ]:
A_sqr = A.T @ A + 0.01 * np.eye(A.shape[1])

In [ ]:
b = 10 * np.random.randn(A.shape[0])

**Задача 1**

Найдите детерминант полученной квадратной матрицы

In [ ]:
#Your code here

**Задача 2**

Сделайте тоже самое, разложив матрицу методом Холецкого и явным образом найдя произведение диагональных элементов

In [ ]:
#Your code here

**Задача 3**

Найдите точное решение задачи A_sqr x = A^T b

In [ ]:
#Your code here

**Задача 4**

Найдите МНК решение задачи Ax = b, сравните с полученным ранее точным решением.

In [ ]:
#Your code here

**Задача 5**

Найдите сингулярные числа матрицы А.

In [ ]:
#Your code here

**Задача 6**

Найдите собственные значения и собственные вектора матрицы A_sqr

In [ ]:
#Your code here